[package]
name = "p2panda"
version = "0.5.1"
edition = "2024"
authors = [
  "adz <x12@adz.garden>",
  "sandreae <contact@samandreae.com>",
  "glyph <glyph@mycelial.technology>",
]
repository = "https://github.com/p2panda/p2panda"
license = "MIT OR Apache-2.0"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
futures-util = { version = "0.3.31", default-features = false }
hex = "0.4.3"
p2panda-core = { path = "../p2panda-core", version = "0.5.1" }
p2panda-net = { path = "../p2panda-net", version = "0.5.1" }
p2panda-store = { path = "../p2panda-store-next", package = "p2panda-store-next", version = "0.5.1" }
pin-project = "1.1.10"
rand = "0.10.0"
rand_chacha = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"

[dev-dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt"] }
